### ISSUE TITLE
Decouple scda - reorganise example and test data samples

### ISSUE THREAD

**Issue by pawelru** [insightsengineering/nestdevs-tasks#1]
As a NEST packages maintainer
In order to have my packages more encapsulated (in particular: independent of scda packages)
I want to move example data into the package while still keeping extensive data testing somewhere else (i.e. new package)

This is the target state:
| package | `tern` / `rlistings` / `rtables` | `scda.tests` | `chevron` | `tmg` / `tmc` / `tg` / `to` | `goshawk` / `osprey` |
|---|---|---|---|---|---|
| test scope | - unit<br>- (general) regression | - (Roche-specific) regression | - unit<br>- (Roche specific) regresion | - unit<br>- shiny | - unit<br>- (general) regression |
| size of data | small | bigger (`scda`) | small | small | small |

I have discussed this with @shajoezhu and here's the summary:
- For each of the repo (starting from `tern` and `rlistings`): please analyse if `scda` dependency is really required. If not: let's create example and testing data (it could be the same data sample) and save it into the respective package. This is assumed to be much _lighter_ than `scda` produces. For some of the cases (e.g. internals to `teal`) it could be non CDISC. 
As a result, a given package would become independent of `scda`. This is relevant for individual package release model. 
This needs to be done for many packages ([basically all downstream dependencies of `scda`](https://github.com/insightsengineering/scda/blob/main/staged_dependencies.yaml#L8-L50)) starting from `tern` and `rlistings`.
- Create a new (private) repo which would just implement data intensive regression tests based on `scda`. Those exist currently in `tern` and it need to be moved from there.

List of tasks:

- [x] create a new (private) repository `scda.tests` (name TBD)
- [x] tern https://github.com/insightsengineering/tern/issues/777
- [x] rlistings 
  - [ ] creating minimal data and regression test
  - [ ] adding Roche listing regression tests to scda.tests (new)
- [ ] chevron
  - [ ] this is very similar to: https://github.com/insightsengineering/chevron/issues/216
- [x] teal https://github.com/insightsengineering/teal/issues/834
- [ ] teal.data https://github.com/insightsengineering/teal.data/issues/145
- [x] teal.slice https://github.com/insightsengineering/teal.slice/issues/299
- [x] teal.transform https://github.com/insightsengineering/teal.transform/issues/133
- [x] teal.widgets https://github.com/insightsengineering/teal.widgets/issues/157
- [x] teal.modules.general https://github.com/insightsengineering/teal.modules.general/issues/532
- [x] teal.modules.clinical https://github.com/insightsengineering/teal.modules.clinical/issues/707
- [x] osprey and teal.osprey https://github.com/insightsengineering/teal.osprey/issues/213
- [x] goshawk and  teal.goshawk https://github.com/insightsengineering/teal.goshawk/issues/222
- [x] teal.modules.hermes https://github.com/insightsengineering/teal.modules.hermes/issues/311
- [ ] teal.modules.helios https://github.com/insightsengineering/teal.modules.helios/issues/88

**Comment by shajoezhu** [comment]
how about we name the new repo as "tlg.tests.scda"

**Comment by Melkiades** [comment]
I widely agree with this issue. Today, I have been thinking about table tests that are currently in `tern` and I found their repetition with the real TLG-c unnecessary and dangerous. Dangerous because it is very easy at the moment to find discrepancies and even tables that are not tested. I would structure `scda.tests` (or `tlg.tests`) so to have all tlgs in only one place (the repo we currently have) while tests just take the output and compare it to saved values generated from the tables. I am strongly against copy-paste the tlg catalog for testing. I think it is prone to errors and updating times take longer and it is possible we forget something, either the current catalog or the testing

**Comment by gogonzo** [comment]
Done!
