### ISSUE TITLE
NEST technical blueprint (#2)

### ISSUE THREAD

**Issue by donyunardi** [insightsengineering/nestdevs-tasks#12]
Continuation of insightsengineering/coredev-tasks#444

### Definition of Done:
Add content on the following topics:
- [x] insightsengineering/nestdevs-tasks#18
- [x] insightsengineering/nestdevs-tasks#19
- [x] insightsengineering/nestdevs-tasks#20
- [x] insightsengineering/nestdevs-tasks#21

**Comment by donyunardi** [comment]
All topics are completed.
@pawelru, please feel free to review the content I have generated thus far. Alternatively, we can also involve the documentation responsible person to provide assistance if needed.
