### ISSUE TITLE
Improve UI of filter panel (5)

### ISSUE THREAD

**Issue by donyunardi** [insightsengineering/nestdevs-tasks#26]
Continuation from #6 

### Summary
For this increment, we will attempt to complete User Requirement #&#8203;2 which is to allow for module-specific default filters.

### Tasks
We have open issue to discuss and research for module-specific default filters:
- [x] https://github.com/insightsengineering/teal.slice/issues/137

After devising a solution proposal, we will proceed to refine it and break it down into smaller issues, ensuring an organized approach to implementing the feature.

### Others
If time permits, we will make an effort to address User Requirement #&#8203;3: Reset button to restore filters to default state. At the very least, we will initiate the research process to gather relevant information.
~- [ ] https://github.com/insightsengineering/nestdevs-tasks/issues/27~ (UX work will be a separate objective for 2023/PI4)
- [x] https://github.com/insightsengineering/teal.slice/issues/298
- [x] https://github.com/insightsengineering/teal.slice/issues/239
