### ISSUE TITLE
Plan for `teal` release on CRAN (Part 2)

### ISSUE THREAD

**Issue by lcd2yyz** [insightsengineering/nestdevs-tasks#28]
Continuation from https://github.com/insightsengineering/NEST-roadmap/issues/85

Steps and prework required to release `teal` and family products on CRAN
- review previous preparation work
- to release teal and family product on CRAN
- discuss possibility of releasing tealverse, similar to tidyverse that can install/load multiple teal and related module packages in one single step
- discuss potential release timeline

### Tasks
- When is the right time to publish to CRAN because things are still changing?
- [x] insightsengineering/nestdevs-tasks#10
- [x] insightsengineering/nestdevs-tasks#1
- [x] https://github.com/insightsengineering/coredev-tasks/issues/447
- [x] Remove all soft-deprecated functions from products (i.e. `chunks` in teal)
- [x] insightsengineering/nestdevs-tasks#11
- [ ] Add `--as-cran` in CICD and rerun pipeline. 
- [ ] Run autovalidateR on all teal packages
- [ ] Fix any R CMD Check Errors/Warnings/Notes from `--as-cran` setup and autovalidateR
- [ ] Discuss and decide whether we want to do `tealverse`

**Comment by donyunardi** [comment]
Moving to #35 
Closing.
