### ISSUE TITLE
switch from `staged-dependencies` to `setup-r-dependencies` for deps install

### ISSUE THREAD

**Issue by pawelru** [insightsengineering/nestdevs-tasks#65]
Our new target solution for installing the dependencies is [`setup-r-dependencies` GHA](https://github.com/insightsengineering/setup-r-dependencies). Currently this is implemented by `deps-installation-method` parameter of most of our higher level actions. The default value is `staged-dependencies` which follows the existing / old logic. The task is to change it to the new value (and resolve issues if any).

More info:
- a PR with that feature: https://github.com/insightsengineering/r.pkg.template/pull/252
- an example of PR to be done: https://github.com/insightsengineering/teal/pull/1361

This is done in that way to conduct migration product by product at its own pace. Then (some time in the future) we will soft deprecate that parameter and archive staged.dependencies at all.

Repos:

### Part 1
- [x] teal.logger https://github.com/insightsengineering/teal.logger/pull/102
- [x] teal.widgets https://github.com/insightsengineering/teal.widgets/pull/274
- [x] teal.code https://github.com/insightsengineering/teal.code/pull/238
- [x] teal.data https://github.com/insightsengineering/teal.data/pull/355
- [x] teal.slice https://github.com/insightsengineering/teal.slice/pull/631
- [x] teal
- [x] teal.transform https://github.com/insightsengineering/teal.transform/pull/227
- [x] teal.reporter https://github.com/insightsengineering/teal.reporter/pull/292
- [x] teal.modules.general https://github.com/insightsengineering/teal.modules.general/pull/815
- [x] teal.modules.clinical https://github.com/insightsengineering/teal.modules.clinical/pull/1297
- [x] teal.goshawk https://github.com/insightsengineering/teal.goshawk/pull/325
- [x] teal.osprey https://github.com/insightsengineering/teal.osprey/pull/289
- [x] teal.modules.helios https://github.com/insightsengineering/teal.modules.helios/pull/143
- [x] teal.modules.hermes https://github.com/insightsengineering/teal.modules.hermes/pull/395

### Part 2
- [x] insightsengineering/nestcolor#77
- [ ] roxy.shinylive
- [x] insightsengineering/formatters#324
- [x] insightsengineering/rtables#940
- [x] insightsengineering/rlistings#229
- [x] insightsengineering/tern.gee#76
- [x] insightsengineering/tern.mmrm#194
- [x] insightsengineering/tern.rbmi#74
- [x] insightsengineering/tern#1340
- [x] insightsengineering/chevron#791
- [x] insightsengineering/dunlin#169
- [x] insightsengineering/citril.metadata#95
- [x] insightsengineering/citril#460
- [x] insightsengineering/cards#350
- [x] insightsengineering/cardx#227
- [x] insightsengineering/random.cdisc.data#321
- [x] osprey https://github.com/insightsengineering/osprey/pull/146
- [x] goshawk https://github.com/insightsengineering/goshawk/pull/261
- [x] helios https://github.com/insightsengineering/helios/pull/661
- [x] hermes https://github.com/insightsengineering/hermes/pull/233
- [x] insightsengineering/tlg-catalog#277
- [x] insightsengineering/scda.test#158
- [ ] verdepcheck
- [x] insightsengineering/rtables.officer#12

**Comment by vedhav** [comment]
🎉All the repos use the `setup-r-dependencies` now!
